config/routes.rb
Rails.application.routes.draw do
  resources :sign_ups, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :channels, except: [:update, :destroy], param: :name do
    resources :messages, only: [:create, :edit, :update]
    resource :membership, only: [:create, :destroy]
  end

  namespace :vent_source do
    resources :events, only: [:index, :show] do
      collection do
        get 'for/:filter_type/:filter_value', action: :index, as: 'filter'
      end
    end

    resources :projections, only: [:index]
  end

  resource :home, only: :show
  root 'homes#show'

  mount ActionCable.server => '/cable'
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = ChannelProjection::Channel.all
  end

  def new
    @create_channel = CreateChannel.new
  end

  def create
    @create_channel = CreateChannel.new create_channel_params

    if @create_channel.valid?
      c = Channel.new
      if @create_channel.execute(c) && c.commit
        @join = JoinChannel.new user_id: current_user.id
        @join.execute(c) && c.commit
        redirect_to channel_path(@create_channel.name)
      else
        render :new
      end
    else
      render :new
    end
  end

  def show
    @channel = ChannelProjection::Channel.find_by name: params[:name]
  end

  private

  def create_channel_params
    params.require(:create_channel).permit(:name)
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def member_of?(channel)
    channel.members.where(person_id: current_user.id).exists?
  end
end

app/views/channels/_message.html.erb
<li id="message-<%= message.message_id %>" class="channel--messages--message">
  <div class="channel--messages--message--member-name"><%= message.member.name %></div>
  <div class="channel--messages--message-text"><%= message.message %></div>
  <div class="channel--messages--message-edit"><%= link_to 'edit', edit_channel_message_path(channel_name: message.channel.name, id: message.message_id) %></div>
</li>

app/views/channels/index.html.erb
<%= link_to 'Add Channel', new_channel_path %>
<ul class="channels">
  <% if @channels.empty? %>
    <div class="channels--empty"></div>
  <% else %>
    <% @channels.each do |channel| %>
      <li class="channels--channel">
        <span class="channels--channel--name"><%= link_to channel.name, channel_path(channel.name) %></span>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/channels/new.html.erb
<%= simple_form_for @create_channel, url: channels_path do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.submit 'Create' %>
<% end %>

app/views/channels/show.html.erb
<div class="channel" id="channel-<%= @channel.aggregate_id %>">
  <header>
    <h1 class="channel--name"><%= @channel.name %></h1>
  </header>
  <div class="channel--members">
    <h2 class="channel--members-count">Members: <%= @channel.members.size %></h2>
    <ul id="channel--member-list">
      <% @channel.members.each do |member| %>
        <li id="<%= member.person_id %>"><%= member.name %></li>
      <% end %>
    </ul>
  </div>
  <% if member_of?(@channel) %>
    <%= button_to 'Leave', channel_membership_path(@channel.name), method: :delete %>
  <% else %>
    <%= button_to 'Join', channel_membership_path(@channel.name), method: :post %>
  <% end %>
  <h2>Messages</h2>
  <ul class="channel--messages">
    <% if @channel.messages.empty? %>
      <div class="channels--messages--emtpy">No messages</div>
    <% else %>
      <% @channel.messages.each do |message| %>
        <%= render 'message', message: message %>
      <% end %>
    <% end %>
  </ul>
  <%= simple_form_for SendMessage.new, url: channel_messages_path(channel_name: @channel.name), remote: true, html: { id: 'new_send_message' } do |f| %>
    <%= f.input 'message', as: :text %>
    <%= f.submit 'Send' %>
  <% end %>
</div>