config/routes.rb
Rails.application.routes.draw do
  resources :sign_ups, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :channels, except: [:update, :destroy], param: :name do
    resources :messages, only: [:create, :edit, :update]
    resource :membership, only: [:create, :destroy]
  end

  namespace :vent_source do
    resources :events, only: [:index, :show] do
      collection do
        get 'for/:filter_type/:filter_value', action: :index, as: 'filter'
      end
    end

    resources :projections, only: [:index]
  end

  resource :home, only: :show
  root 'homes#show'

  mount ActionCable.server => '/cable'
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = VentSource::ArEventStore::Event.all
    apply_filters
  end

  def show
    @event = VentSource::ArEventStore::Event.find_by(event_id: params[:id])
    raise ActiveRecord::RecordNotFound unless @event
  end

  private

  def apply_filters
    if params[:filter_type]
      @events = @events.where(params[:filter_type] => params[:filter_value])
    end
  end
end

app/controllers/vent_source/events_controller.rb
class VentSource::EventsController < ApplicationController
  def index
    @events = VentSource::ArEventStore::Event.all
    apply_filters
  end

  def show
    @event = VentSource::ArEventStore::Event.find_by(event_id: params[:id])
    raise ActiveRecord::RecordNotFound unless @event
  end

  private

  def apply_filters
    if params[:filter_type]
      @events = @events.where(params[:filter_type] => params[:filter_value])
    end
  end
end

app/controllers/vent_source/projections_controller.rb
class VentSource::ProjectionsController < ApplicationController
  def index
    @projections = VentSource::Projections.projections.map(&:new)
  end
end

app/views/vent_source/events/index.html.erb
<% if @events.empty? %>
  <div>No events</div>
<% else %>
  <table class="events">
    <tr>
      <th>event_id</th>
      <th>name</th>
      <th>aggregate_id</th>
      <th>aggregate_type</th>
      <th>created_at</th>
    </tr>
    <% @events.each do |event| %>
      <tr class="event">
        <td><%= link_to event.event_id, vent_source_event_path(event.event_id) %></td>
        <td><%= link_to event.name, filter_vent_source_events_path(:name, event.name) %></td>
        <td><%= link_to event.aggregate_id, filter_vent_source_events_path(:aggregate_id, event.aggregate_id) %></td>
        <td><%= link_to event.aggregate_type, filter_vent_source_events_path(:aggregate_type, event.aggregate_type) %></td>
        <td><%= event.created_at %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/vent_source/events/show.html.erb
        <dl>
        <dt>event_id</dt><dd><%= @event.event_id %></dd>
          <dt>name<dt><dd><%= @event.name %></dd>
          <dt>aggregate_id</dt><dd><%= @event.aggregate_id %></dt>
          <dt>aggregate_type</dt> <dd><%= @event.aggregate_type %></dd>
          <dt>version</dt> <dd><%= @event.version %></dd>
          <dt>sequence_number</dt> <dd><%= @event.sequence_number %></dd>
          <dt>created_at</dt> <dd><%= @event.created_at %></dd>
        </dl>
        data:
        <dl>
          <% @event.data.each do |key, value| %>
            <dt><%= key %><dt> <dd> <%= value %> </dd>
          <% end %>
        </dl>