config/routes.rb
Rails.application.routes.draw do
  resources :sign_ups, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :channels, except: [:update, :destroy], param: :name do
    resources :messages, only: [:create, :edit, :update]
    resource :membership, only: [:create, :destroy]
  end

  namespace :vent_source do
    resources :events, only: [:index, :show] do
      collection do
        get 'for/:filter_type/:filter_value', action: :index, as: 'filter'
      end
    end

    resources :projections, only: [:index]
  end

  resource :home, only: :show
  root 'homes#show'

  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render "flashes" -%>
  <% unless no_auth_controls? %>
    <header>
      <span id="logo">
        <%= image_tag("slacks-small.png", alt: t('titles.application'), height: '50px', width: '50px') %>
        <span class="logo-name"><%= t('titles.application') %></span>
      </span>

      <nav class="app-nav">
        <ul>
          <% if signed_in? %>
            <li class="app-nav--item"><%= link_to 'Channels', channels_path %></li>
            <li class="app-nav--item app-nav--item--auth"><%= button_to 'Sign out', session_path, method: :delete %></li>
          <% else %>
            <li class="app-nav--item app-nav--item--auth"><%= link_to 'Sign up', new_sign_up_path %></li>
          <% end %>
        <ul>
      </nav>
    </header>
  <% end %>

  <%= yield %>
  <%= render "javascript" %>
</body>
</html>